import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  center: { flex: 1, justifyContent: "center", alignItems: "center" },
  imageContainer: {
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
    minHeight: 200,
  },
  productImage: { width: 200, height: 200 },
  infoContainer: { padding: 20 },
  brandName: { color: "#888", fontSize: 14, marginBottom: 4 },
  productName: { fontSize: 22, fontWeight: "bold", marginBottom: 8 },

  optionSelectorContainer: {
    marginVertical: 15,
    padding: 12,
    backgroundColor: "#F9F9F9",
    borderRadius: 8,
  },
  optionLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 8,
    fontWeight: "600",
  },
  optionScroll: {
    flexDirection: "row",
  },
  optionChip: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#DDD",
    marginRight: 8,
  },
  optionChipActive: {
    backgroundColor: "#FF2D78",
    borderColor: "#FF2D78",
  },
  optionChipText: {
    fontSize: 12,
    color: "#666",
  },
  optionChipTextActive: {
    color: "#fff",
    fontWeight: "bold",
  },

  priceRow: { flexDirection: "row", alignItems: "center", marginTop: 4 },
  price: { fontSize: 20, fontWeight: "600", color: "#FF2D78", marginRight: 10 },
  ratingBadge: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#FFF8E1",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  ratingText: { fontWeight: "bold", marginLeft: 4, color: "#333" },
  bookmarkButton: {
    position: "absolute",
    right: 20,
    top: 20,
    alignItems: "center",
  },
  divider: { height: 8, backgroundColor: "#F4F4F4" },
  section: { padding: 20 },
  sectionTitle: { fontSize: 18, fontWeight: "bold", marginBottom: 15 },

  infoSectionContainer: { backgroundColor: "#fff" },
  expandableContainer: { borderBottomWidth: 1, borderBottomColor: "#eee" },
  expandableHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#fff",
  },
  expandableTitle: { fontSize: 16, fontWeight: "600", color: "#333" },
  expandableContent: {
    paddingHorizontal: 20,
    paddingBottom: 20,
    backgroundColor: "#fdfdfd",
  },
  infoRow: { flexDirection: "row", marginBottom: 8 },
  infoLabel: { width: 100, fontSize: 14, color: "#888", fontWeight: "500" },
  infoValue: { flex: 1, fontSize: 14, color: "#333" },
  longTextContainer: { marginBottom: 10 },
  longTextLabel: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 4,
  },
  longTextValue: { fontSize: 14, color: "#555", lineHeight: 20 },
  infoDesc: { fontSize: 13, color: "#666", lineHeight: 18 },

  compositionContainer: { marginTop: 10, marginBottom: 20 },
  compositionLabels: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 10,
    flexWrap: "wrap",
  },
  compLabel: {
    fontSize: 14,
    fontWeight: "bold",
    marginRight: 10,
    color: "#333",
  },
  compValue: { color: "#666", fontWeight: "normal" },
  compBadge: {
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    marginRight: 6,
  },
  compBadgeText: { fontSize: 11, fontWeight: "bold" },
  graphBar: {
    flexDirection: "row",
    height: 10,
    borderRadius: 5,
    overflow: "hidden",
    backgroundColor: "#F0F0F0",
    width: "100%",
  },

  dividerThin: { height: 1, backgroundColor: "#EEE", marginVertical: 10 },
  alertContainer: { marginTop: 10 },
  alertRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
  },
  alertLeft: { flexDirection: "row", alignItems: "center" },
  alertTitle: { fontSize: 14, color: "#555", marginLeft: 8 },
  alertCount: { fontSize: 14, fontWeight: "bold" },
  alertDetailText: {
    fontSize: 12,
    color: "#888",
    paddingLeft: 26,
    paddingBottom: 10,
    lineHeight: 18,
  },

  harmfulListContainer: {
    marginTop: 15,
    backgroundColor: "#FFF0F0",
    padding: 15,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#FFCDD2",
  },
  harmfulItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 4,
  },
  harmfulName: { fontSize: 14, color: "#333" },
  harmfulReason: { fontSize: 14, color: "#D32F2F", fontWeight: "600" },

  purposeRow: {
    flexDirection: "row",
    alignItems: "flex-start",
    marginBottom: 15,
    paddingVertical: 5,
  },
  purposeIconContainer: {
    width: 36,
    height: 36,
    borderRadius: 18,
    justifyContent: "center",
    alignItems: "center",
    marginRight: 12,
  },
  purposeTextContainer: {
    flex: 1,
  },
  purposeTitle: {
    fontSize: 14,
    fontWeight: "bold",
    marginBottom: 4,
  },
  purposeListText: {
    fontSize: 13,
    color: "#666",
    lineHeight: 18,
  },

  rowBetween: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 15,
  },
  writeReviewText: { color: "#FF2D78", fontWeight: "600" },
  reviewItem: {
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    paddingVertical: 15,
  },
  reviewHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 6,
  },
  reviewerName: { fontWeight: "bold", fontSize: 14 },
  reviewerInfo: { flex: 1 },
  reviewActions: { flexDirection: "row", alignItems: "center" },
  actionBtn: { marginLeft: 12, paddingVertical: 4 },
  actionBtnText: { fontSize: 13, color: "#888", fontWeight: "500" },
  starRow: { flexDirection: "row", marginTop: 2 },
  reviewContent: {
    fontSize: 14,
    color: "#333",
    lineHeight: 20,
    marginBottom: 4,
  },
  reviewDate: { fontSize: 12, color: "#aaa" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.5)",
    justifyContent: "center",
    padding: 20,
  },
  modalContent: { backgroundColor: "#fff", borderRadius: 16, padding: 20 },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 20,
  },
  starInputRow: {
    flexDirection: "row",
    justifyContent: "center",
    marginBottom: 20,
  },
  textInput: {
    height: 100,
    borderColor: "#ddd",
    borderWidth: 1,
    borderRadius: 8,
    padding: 10,
    textAlignVertical: "top",
    marginBottom: 20,
  },
  modalButtons: { flexDirection: "row", justifyContent: "space-between" },
  cancelBtn: {
    flex: 1,
    padding: 15,
    backgroundColor: "#eee",
    borderRadius: 8,
    marginRight: 10,
    alignItems: "center",
  },
  submitBtn: {
    flex: 1,
    padding: 15,
    backgroundColor: "#FF2D78",
    borderRadius: 8,
    alignItems: "center",
  },
});